name: :rocket: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: :test_tube: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download deps
        run: npm ci

      - name: Lint
        run: npm run lint

  jest:
    name: :black_joker: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download deps
        run: npm ci

      - name: Test
        run: npm run test